"""Pre-set mock company data for Demo Mode (V6.0)."""

MOCK_COMPANIES = {
    "Anduril Industries": {
        "trl_score": 9,
        "ip_score": 1.0,
        "complexity_score": 0.6,
        "platform_potential": 0.9,
        "integration_friction": 0.7,
        "dual_use_score": 0.95,
        "regulatory_score": 0.8,
        "mrl_score": 8,
        "rnd_years": 2.0,
        "market_cagr": 0.15,
        "urgency_score": 0.95,
        "moat_score": 0.9,
        "supply_chain_risk": 0.8,
        "team_has_phd": True,
        "team_has_exit": True,
        "is_tier1_background": True,
        "founders_worked_together": True,
        "is_solo_founder": False,
        "all_scientists": False,
        "all_biz": False,
        "sentiment": "Positive",
        "is_miracle_tech": False,
        "entry_valuation": 50.0,
    },
    "Avalanche Energy": {
        "trl_score": 4,
        "ip_score": 0.5,
        "complexity_score": 0.3,
        "platform_potential": 0.8,
        "integration_friction": 1.0,
        "dual_use_score": 0.95,
        "regulatory_score": 0.5,
        "mrl_score": 3,
        "rnd_years": 7.0,
        "market_cagr": 0.40,
        "urgency_score": 0.8,
        "moat_score": 0.8,
        "supply_chain_risk": 0.6,
        "team_has_phd": True,
        "team_has_exit": False,
        "is_tier1_background": True,
        "founders_worked_together": True,
        "is_solo_founder": False,
        "all_scientists": False,
        "all_biz": False,
        "sentiment": "Neutral",
        "is_miracle_tech": True,
        "entry_valuation": 12.0,
    },
    "Humane": {
        "trl_score": 8,
        "ip_score": 1.0,
        "complexity_score": 0.7,
        "platform_potential": 0.4,
        "integration_friction": 0.2,
        "dual_use_score": 0.5,
        "regulatory_score": 0.8,
        "mrl_score": 7,
        "rnd_years": 5.0,
        "market_cagr": 0.05,
        "urgency_score": 0.1,
        "moat_score": 0.3,
        "supply_chain_risk": 0.5,
        "team_has_phd": True,
        "team_has_exit": True,
        "is_tier1_background": True,
        "founders_worked_together": True,
        "is_solo_founder": False,
        "all_scientists": False,
        "all_biz": False,
        "sentiment": "Negative",
        "is_miracle_tech": False,
        "entry_valuation": 100.0,
    },
}
