"""Pre-set mock company data for Demo Mode (V6.0 + Variable Valuation + Score Justifications)."""

MOCK_COMPANIES = {
    "Anduril Industries": {
        # V6 factors
        "trl_score": 9,
        "trl_reason": "Systems deployed in production; Lattice and Ghost already fielded with DoD and border agencies.",
        "ip_score": 1.0,
        "ip_reason": "Extensive patent portfolio in autonomous systems and C2; granted IP across core stack.",
        "complexity_score": 0.6,
        "complexity_reason": "Hardware-heavy autonomy with proven software layer; not pure software but not unproven science.",
        "platform_potential": 0.9,
        "platform_potential_reason": "Lattice OS and hardware family support multiple domains (air, sea, land) and future verticals.",
        "integration_friction": 0.7,
        "integration_friction_reason": "High score due to modular architecture and API-first design; some custom integration for classified networks.",
        "dual_use_score": 0.95,
        "dual_use_reason": "Currently executing major contracts for both US SOCOM (Defense) and Border Patrol (Civil).",
        "regulatory_score": 0.8,
        "regulatory_reason": "Clear path via existing DoD and DHS frameworks; no novel FDA or NRC exposure.",
        "mrl_score": 8,
        "mrl_reason": "Mass production established at Lattice factory; shipping thousands of units.",
        "rnd_years": 2.0,
        "rnd_reason": "Products already in field; R&D focused on next-gen variants, not first deployment.",
        "market_cagr": 0.15,
        "market_cagr_reason": "Defense and dual-use autonomy growing steadily; budget tailwinds and geopolitical demand.",
        "urgency_score": 0.95,
        "urgency_reason": "High score due to active DoD contracts and strategic national security demand.",
        "moat_score": 0.9,
        "moat_reason": "Lattice OS creates a network effect; hardware is commoditized but software is sticky.",
        "supply_chain_risk": 0.8,
        "supply_chain_reason": "US-based manufacturing and qualified supply chain for defense; limited single-source exposure.",
        "team_has_phd": True,
        "team_has_exit": True,
        "is_tier1_background": True,
        "founders_worked_together": True,
        "is_solo_founder": False,
        "all_scientists": False,
        "all_biz": False,
        "sentiment": "Positive",
        "is_miracle_tech": False,
        "entry_valuation": 12500.0,
        "estimated_entry_val": 12500.0,
        "estimated_base_exit": 20000.0,
        "estimated_home_run_exit": 100000.0,
        "valuation_source": "Tier 1: Derived from Series F (2024) & Palantir Comps",
    },
    "Avalanche Energy": {
        # V6 factors
        "trl_score": 4,
        "trl_reason": "Lab-scale fusion demonstrations; physics validated but not yet at reactor-relevant scale.",
        "ip_score": 0.5,
        "ip_reason": "Patent applications in compact fusion; pending status given early stage.",
        "complexity_score": 0.3,
        "complexity_reason": "New science: fusion requires unproven physics and engineering at scale.",
        "platform_potential": 0.8,
        "platform_potential_reason": "Fusion works could enable power, propulsion, and industrial heat; multiple verticals.",
        "integration_friction": 1.0,
        "integration_friction_reason": "Plug-in power or heat offtake; utilities and DoD would integrate as standard offtakers.",
        "dual_use_score": 0.95,
        "dual_use_reason": "DoD interest in compact fusion for propulsion and power; clear commercial utility demand.",
        "regulatory_score": 0.5,
        "regulatory_reason": "Nuclear-adjacent; NRC path exists but regulatory framework for compact fusion still evolving.",
        "mrl_score": 3,
        "mrl_reason": "Prototype-stage hardware; no production line yet; manufacturing scale is years out.",
        "rnd_years": 7.0,
        "rnd_reason": "Fusion timeline is long; 5–10 years to commercial pilot is sector norm.",
        "market_cagr": 0.40,
        "market_cagr_reason": "Clean tech and fusion investment growing fast; policy and climate driving capital.",
        "urgency_score": 0.8,
        "urgency_reason": "Energy security and decarbonization create strong pull; DoD adds strategic urgency.",
        "moat_score": 0.8,
        "moat_reason": "Proprietary physics and reactor design; first-mover in compact fusion could define category.",
        "supply_chain_risk": 0.6,
        "supply_chain_reason": "Some specialized components and materials; mix of domestic and international sourcing.",
        "team_has_phd": True,
        "team_has_exit": False,
        "is_tier1_background": True,
        "founders_worked_together": True,
        "is_solo_founder": False,
        "all_scientists": False,
        "all_biz": False,
        "sentiment": "Neutral",
        "is_miracle_tech": True,
        "entry_valuation": 40.0,
        "estimated_entry_val": 40.0,
        "estimated_base_exit": 300.0,
        "estimated_home_run_exit": 15000.0,
        "valuation_source": "Tier 2: Derived from Sector Multiples (Clean Tech Series A)",
    },
    "Humane": {
        # V6 factors
        "trl_score": 8,
        "trl_reason": "Pin and AI stack shipped in product form; hardware and software integrated at scale.",
        "ip_score": 1.0,
        "ip_reason": "Granted patents in wearable AI and interface; strong IP around form factor and interaction.",
        "complexity_score": 0.7,
        "complexity_reason": "Hardware plus AI; complex but not unproven science; execution risk is main variable.",
        "platform_potential": 0.4,
        "platform_potential_reason": "Focused on single product and AI pin use case; limited evidence of broader platform play.",
        "integration_friction": 0.2,
        "integration_friction_reason": "Consumer device; low integration for end user but adoption and distribution are friction.",
        "dual_use_score": 0.5,
        "dual_use_reason": "Primarily consumer; no material government or dual-use contracts cited.",
        "regulatory_score": 0.8,
        "regulatory_reason": "Consumer electronics path; no FDA or heavy regulatory overlay.",
        "mrl_score": 7,
        "mrl_reason": "Mass production of Pin achieved; supply chain and manufacturing proven despite demand issues.",
        "rnd_years": 5.0,
        "rnd_reason": "Product launched; remaining R&D is iteration and software, not first-of-kind hardware.",
        "market_cagr": 0.05,
        "market_cagr_reason": "Consumer AI wearables niche; growth uncertain and sentiment negative post-launch.",
        "urgency_score": 0.1,
        "urgency_reason": "Vitamin not painkiller; no critical need or government pull driving demand.",
        "moat_score": 0.3,
        "moat_reason": "Weak lock-in; commoditized AI and hardware; brand and distribution under pressure.",
        "supply_chain_risk": 0.5,
        "supply_chain_reason": "Standard consumer electronics supply chain; some concentration risk but not defense-critical.",
        "team_has_phd": True,
        "team_has_exit": True,
        "is_tier1_background": True,
        "founders_worked_together": True,
        "is_solo_founder": False,
        "all_scientists": False,
        "all_biz": False,
        "sentiment": "Negative",
        "is_miracle_tech": False,
        "entry_valuation": 850.0,
        "estimated_entry_val": 850.0,
        "estimated_base_exit": 100.0,
        "estimated_home_run_exit": 2500.0,
        "valuation_source": "Tier 1: Derived from Series C (2023) - Down Round Risk",
    },
}
